# Run fast tests for PR (fewer OSes, fewer python versions)
name: Fast Tests ðŸš€

on:
  pull_request:

jobs:
  tests:
    uses: ./.github/workflows/build-and-run-tests.yml
    with:
      test-mode: fast
    permissions:
      contents: read
      security-events: write

# Disable all permissions by default at workflow level
permissions: {}
